// Generated by CoffeeScript 1.6.2
(function() {
  var application, everyone, nowjs, port, server;

  application = require("./.app/")();

  nowjs = require("now");

  if (!process.env.NODE_ENV) {
    process.env.NODE_ENV = "local";
  }

  port = process.env.PORT || process.env.VMC_APP_PORT || process.env.VCAP_APP_PORT || 3000;

  server = application.listen(port);

  everyone = nowjs.initialize(server);

  console.log("Server running at http://127.0.0.1: " + port + "\nPress CTRL-C to stop server.");

}).call(this);
