// Generated by CoffeeScript 1.6.2
(function() {
  var app, everyone, nowjs, port, server;

  app = require("./.app/")();

  nowjs = require("now");

  port = process.env.PORT || process.env.VMC_APP_PORT || process.env.VCAP_APP_PORT || 3000;

  server = app.listen(port);

  everyone = nowjs.initialize(server);

  console.log("Server running at http://127.0.0.1: " + port + "\nPress CTRL-C to stop server.");

}).call(this);
